version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  build:
    commands:
      - aws --version
      - node --version
      - npm --version
      - ls -lha
      - npm run appspec
      - ls -lha
artifacts:
  files:
    - appspec.json
  discard-paths: yes